name: Build

on: [push, pull_request]

jobs:
#  build-macos-amd64:
#    runs-on: macos-latest

#    steps:
#    - uses: actions/checkout@v2
#    - name: Build macos-amd64
#      run: |
#        scripts/build-macos-amd64.sh

  build-macos-arm:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v2
    - name: Build macos-arm
      run: |
        scripts/build-macos-arm.sh
    - name: Create artifacts dir
      run: |
          mkdir -p ./artifacts
          cd ./artifacts
          cp -r ../build ../portal_game ./
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        path: ./artifacts
        if-no-files-found: error
